name: Run BankingApp Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore Dependencies
      run: dotnet restore BankingApp.Tests/BankingApp.Tests.csproj

    - name: Run Tests with GitHub Secret
      env:
        DB_API_URL_CLDFLR: ${{ secrets.DB_API_URL_CLDFLR }}
        DB_ACCESS_KEYCLDFLF_TOKEN: ${{ secrets.DB_ACCESS_KEYCLDFLF_TOKEN }}
      run: dotnet test BankingApp.Tests/BankingApp.Tests.csproj --no-restore --verbosity normal